languages:
  English:
    code: "en_US"
    is_default: true
  Português:
    code: "pt_BR"

models:
  Llama3:
    code: "llama3"
    is_default: true
  Gemma:
    code: "gemma"
  Llama3-Gradient:
    code: "llama3-gradient"

codegen_models:
  CodeLlama:
    code: "codellama"
    is_default: true


datasets:
  Netflix:
    url: ../data/netflix_titles.csv
    metadata: ../data/netflix-movies-and-tv-shows-metadata.json